import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${playfair.variable} antialiased min-h-screen flex flex-col bg-slate-50`}
      >
        {/* Stylish Header */}
        <header className="w-full bg-white/80 backdrop-blur-md border-b border-slate-200 sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
            <a href="/" className="font-outfit text-2xl font-bold tracking-tighter text-slate-900">
              LEADDESK<span className="text-blue-600">MINI</span>
            </a>
          </div>
        </header>

        <main className="flex-grow">
          {children}
        </main>
        
        {/* Updated Footer */}
        <footer className="w-full py-8 bg-white border-t border-slate-200">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-slate-500">
            <div className="flex flex-col sm:flex-row gap-2 sm:gap-6 items-center">
              <span className="font-medium text-slate-700">Junaid Biswas</span>
              <a href="tel:+919907927383" className="hover:text-blue-600 transition-colors">+91 9907927383</a>
              <a href="https://instagram.com/junaid_biswas_05" target="_blank" rel="noopener noreferrer" className="hover:text-pink-600 transition-colors">
                IG: @junaid_biswas_05
              </a>
              <a href="https://github.com/Junaidbiswas05" target="_blank" rel="noopener noreferrer" className="hover:text-slate-900 transition-colors">
                GitHub: Junaidbiswas05
              </a>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-2 sm:gap-6 items-center">
              <a
                href="https://digitalheroesco.com"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-blue-600 transition-colors hover:underline font-medium"
              >
                Built for Digital Heroes Training Task
              </a>
              <a href="/admin" className="hover:text-blue-600 transition-colors font-medium text-slate-700">
                Admin Login
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
